### ISSUE TITLE
AWX is now requiring python3

### ISSUE THREAD

**Issue by chrisrohr** [agardnerIT/ansible-playbook-awx#3]
Thank you for writing this up as I spent a lot of time trying to get the galaxy role you mentioned working on Amazon Linux to no avail.  I noticed, however, that at some point the AWX install playbook now requires python3.  This causes a number of issues because you can't just switch the interpreter to python3 as it will break the yum module.  Here is what I had to do to get this to work:

First I had to check and install Python3
```
    - name: Check to see if python3 is already installed
      command: "python3 --version"
      ignore_errors: true
      changed_when: false #read-only task
      check_mode: no
      register: python3_is_installed

    - name: Install Python 3
      yum:
        name: python3
```

Then I had to update the following tasks:

```
    - name: Install Ansible
      pip:
        name: ansible
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python3

    #... Existing yum, git, service tasks remained the same ....

    - name: Install Docker Compose
      pip:
        name: docker-compose==1.9.0
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install AWX
      command: /usr/local/bin/ansible-playbook -i /tmp/ansible/installer/inventory /tmp/ansible/installer/install.yml
      vars:
        ansible_python_interpreter: /usr/bin/python3
```

Then it all worked like a charm.
